# TODO: auto tags with https://docs.docker.com/build/ci/github-actions/manage-tags-labels/

name: CI

# on:
#   push:
#     branches:
#       - 'main'
on:
  push:
    tags:
      - '*'

jobs:
  docker: # Should run after the npm package was published
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Extract tag name'
        shell: bash
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        id: extract_tag
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dht-relay-wss:${{ steps.extract_tag.outputs.tag }}, ${{ secrets.DOCKER_HUB_USERNAME }}/dht-relay-wss:latest
          build-args: TAG=${{ steps.extract_tag.outputs.tag }}
