# TODO: auto tags with https://docs.docker.com/build/ci/github-actions/manage-tags-labels/

name: CI

# on:
#   push:
#     branches:
#       - 'main'
on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: 'print test'
        run: echo ${{ env.GITHUB_REF }}
      -
        name: 'more print test'
        run: echo $GITHUB_REF
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: hdegroote/dht-relay-wss:latest
          build-args: ${{ env.GITHUB_REF }} # Should fail
