# TODO: auto tags with https://docs.docker.com/build/ci/github-actions/manage-tags-labels/

name: CI

# on:
#   push:
#     branches:
#       - 'main'
on:
  push:
    tags:
      - '*'

jobs:
  docker: # Should run after the npm package was published
    runs-on: ubuntu-latest
    steps:
      -
        name: 'printing the tag'
        run: echo ${{ github.ref##*/ }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: hdegroote/dht-relay-wss:${{ github.ref##*/ }}
          build-args: TAG=${{ github.ref##*/ }}
